### ISSUE TITLE
[BUG] Conditional nodes leaking to parent scope [PRT-84]

### ISSUE THREAD

**Issue by heyvito** [Gympass/go-giter8#5]
Considering the following input:

```
$if(parent.truthy)$
Parent OK
$if(child.truthy)$
Child OK
$endif$
$endif$
```

The parsed AST becomes:

```
Conditional
   Expression: parent.truthy
   Then:
    - Literal(Parent OK)
   Else: nil
   ElseIf: nil
Conditional
   Expression: child.truthy
   Then:
    - Literal(Child OK)
   Else: nil
   ElseIf: nil
```

When the following is expected, instead:

```
Conditional
   Expression: parent.truthy
   Then:
    - Literal(Parent OK)
    - Conditional
      Expression: child.truthy
      Then:
       - Literal(Child OK)
      Else: nil
      ElseIf: nil
   Else: nil
   ElseIf: nil
```
